config/routes.rb
Rails.application.routes.draw do
  root :to => 'events#index'

  get '/auth/twitter/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'

  get '/logout' => 'sessions#destroy'

  resources :users, only: [:show]
  resources :events do
    member do
      get '/atend' => 'atendees#atend'
      get '/absent' => 'atendees#absent'
    end
  end

end

app/models/atendee.rb
class Atendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :status, presence: true

  enum status: { attended: 0, absented: 1 }
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :atendees

  validates :title, presence: true, length: { maximum: 255 }
  validates :hold_at, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true }
  validates :location, presence: true, length: { maximum: 255 }
  validates :owner, presence: true, length: { maximum: 255 }
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_many :atendees

  validates :uid, presence: true, numericality: { only_integer: true }
  validates :name, presence: true, length: { maximum: 255 }
  validates :nickname, presence: true, length: { maximum: 255 }
  validates :image, presence: true
  validates :token, presence: true#, length: { is: 50 }
  validates :secret, presence: true#, length: { is: 45 }

  def self.find_or_create_from_twitter(omniauth)
    find_or_create_by(uid: omniauth[:uid]) do |user|
      user.uid = omniauth[:uid]
      user.name = omniauth[:info][:name]
      user.nickname = omniauth[:info][:nickname]
      user.image = omniauth[:info][:image]
      user.description = omniauth[:info][:description]
      user.token = omniauth[:credentials][:token]
      user.secret = omniauth[:credentials][:secret]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def login_required
    unless logged_in?
      flash[:alert] = 'Please login first.'
      redirect_to events_url
    end
  end
end

app/controllers/atendees_controller.rb
class AtendeesController < ApplicationController
  before_action :login_required, only: [:atend, :absent]
  before_action :set_event, only: [:atend, :absent]
  before_action :set_atendee_params, only: [:atend, :absent]

  def atend
    atendee = Atendee.find_or_create_by @atendee_params
    case atendee.status
    when 'attended'
      flash[:notice] = 'Already atended'
    when 'absented'
      flash[:alert] = 'Error something' unless atendee.update(status: 'attended')
    else
      atendee = Atendee.new @atendee_params.merge(status: 'attended')
      flash[:alert] = 'Error something' unless atendee.save
    end

    redirect_to event_path @event
  end

  def absent
    atendee = Atendee.find_by @atendee_params
    flash[:alert] = 'Error something' unless atendee.update(status: 'absented')

    redirect_to event_path @event
  end

  private

  def set_event
    @event = Event.find params[:id]
  end

  def set_atendee_params
    @atendee_params = { user_id: current_user.id, event_id: @event.id }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :login_required, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params.merge(user_id: current_user.id))

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.fetch(:event, {}).permit(:title, :hold_at, :capacity, :location, :owner, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_twitter(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to events_url
  end

  def destroy
    reset_session
    # TODO: fix redirect link
    redirect_to events_url
  end

  def failure
    flash[:alert] = 'login failure'
    # TODO: fix redirect link
    redirect_to events_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def already_atended?
    !!Atendee.find_by(event_id: params[:id], user_id: current_user.id, status: 'attended')
  end
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :title %> <%= f.text_field :title %><br>
  <%= f.label :hold_at %> <%= f.datetime_select :hold_at %><br>
  <%= f.label :capacity %> <%= f.number_field :capacity %><br>
  <%= f.label :location %> <%= f.text_field :location %><br>
  <%= f.label :owner %> <%= f.text_field :owner %><br>
  <%= f.label :description %> <%= f.text_area :description %><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>title</th>
      <th>description</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <% if logged_in? %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if logged_in? %>
  <%= link_to 'New Event', new_event_path %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<dl>
  <dt>title</dt>
  <dd><%= @event.title %></dd>
  <dt>hold at</dt>
  <dd><%= @event.hold_at %></dd>
  <dt>capacity</dt>
  <dd><%= @event.capacity %></dd>
  <dt>location</dt>
  <dd><%= @event.location %></dd>
  <dt>owner</dt>
  <dd><%= @event.owner %></dd>
  <dt>description</dt>
  <dd><%= simple_format(h @event.description) %></dd>
</dl>

attendance
<ul id="attendance">
  <% @event.atendees.attended.each do |atendee| %>
  <li><%= image_tag atendee.user.image %> <%= link_to atendee.user.name, user_path(atendee.user) %></li>
<% end %>
</ul>
<br>
absence
<ul id="absence">
  <% @event.atendees.absented.each do |atendee| %>
    <li><%= image_tag atendee.user.image %> <%= link_to atendee.user.name, user_path(atendee.user) %></li>
  <% end %>
</ul>


<% if logged_in? %>
  <% if already_atended? %>
    <%= link_to 'Absent', absent_event_path(@event) %>
  <% else %>
    <%= link_to 'Atend', atend_event_path(@event) %>
  <% end %>
  <br>
  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Destroy', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NearAtnd</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <div>
      <% if logged_in? %>
        login as <%= current_user.name %> <%= link_to 'log-out', logout_path %>
      <% else %>
        <%= link_to 'log-in with Twitter', '/auth/twitter' %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>User detail</h1>
<div>
  <%= image_tag @user.image %>
</div>
<ul>
  <li>uid: <%= @user.uid %></li>
  <li>name: <%= @user.name %></li>
  <li>nickname: <%= @user.nickname %></li>
  <li>description: <%= @user.description %></li>
</ul>